reviews/urls.py
"""
URLs configuration for Reviews 

"""
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^my-reviews/$', views.reviews_list, name="list_my_reviews"),
    url(r'^business-reviews/$', views.reviews_list, name="list_business_reviews"),
    url(r'^create/(?P<pk>\d+)/$', views.create_review, name="create"),
    url(r'^(?P<pk>\d+)/edit$', views.edit_review, name="edit"),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_review, name="delete"),
]

spotimist/urls.py
from business import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from activities.views import (
    home_page,
    home_about_page,
    dashboard,
    dashboard_business,
    dashboard_user_activities,
    blog_page,
    blog_post,
    get_listed,
    home_page_v2
)

from business.views import business_detail, dashboard_get_app
from business.serializers import BusinessViewSet, BusinessList, BusinessDetail, CategoryViewSet
from services.models import RecurringService, Occurrence
from services.views import services_list, services_create, services_edit, services_delete, occurences_json

from bookings.serializers import BookingDetail, BookingItemDetail

from activities.models import Activity, OpeningHours
from activities.seralizers import ActivityViewSet
from services.serializers import RecurringServiceViewSet
from rest_framework import routers, serializers, viewsets, generics

from support.views import contact_form, support_list, support_detail


# Routers provide an easy way of automatically determining the URL conf.

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
router.register(r'activities', ActivityViewSet)
# router.register(r'businesses', BusinessViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'recurring-services', RecurringServiceViewSet)
# router.register(r'openinghours', OpeningHoursViewSet)

if settings.ENABLE_TWO_FACTOR_ADMIN:
    from django_otp.admin import OTPAdminSite
    admin.site.__class__ = OTPAdminSite

urlpatterns = [
    url(r'^$', home_page_v2, name='home'),
    
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include("accounts.urls", namespace="profile")),
    url(r'^home-v2/', home_page, name='home-v2'),
    url(r'^home-about/', home_about_page, name='home-about'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^dashboard-business/$', dashboard_business, name='dashboard-business'),
    url(r'^dashboard-business/get-app/', dashboard_get_app, name='dashboard-get-app'),
    url(r'^dashboard/my-activities/$', dashboard_user_activities, name='dashboard_user_activities'),
    url(r'^blog/', blog_page, name='blog'),
    url(r'^spotimist-day-1/', blog_post, name='blog_post'),
    url(r'^dashboard/support/$', support_list, name='support_list'),
    url(r'^dashboard/support/(?P<pk>[0-9]+)/$', support_detail, name='support_detail'),
    url(r'^contact/', contact_form, name='contact'),
    url(r'^get-listed/', get_listed, name='get-listed'),

    url(r'^activities/', include("activities.urls", namespace="activities")),
    url(r'^bookings/', include("bookings.urls", namespace="bookings")),
    url(r'^business/', include("business.urls", namespace="business")),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^spotmin/', admin.site.urls),
    url(r'^privacy-policy/', TemplateView.as_view(template_name="privacy_policy.html"), name='privacy'),
    url(r'^terms-and-conditions/', TemplateView.as_view(template_name="terms_and_conditions.html"), name='tandc'),
    url(r'^booking-terms-and-conditions/', TemplateView.as_view(template_name="booking_terms_and_conditions.html"),
        name='btandc'),

    url(r'api/businesses/$', BusinessList.as_view(), name="api-business-list"),
    url(r'api/business-detail/(?P<pk>[0-9]+)/$', BusinessDetail.as_view(), name="business-detail"),
    url(r'api/booking-detail/(?P<booking_id>\w+)/(?P<business_id>[0-9]+)/$', BookingDetail.as_view(),
        name="booking-detail"),
    url(r'api/bookingitem-detail/(?P<pk>[0-9]+)/$', BookingItemDetail.as_view(), name="bookingitem-detail"),
    url(r'api/', include(router.urls)),
    url(r'^rest-auth/', include('rest_auth.urls')),

    url(r'listings/', views.FilterView.as_view(), name="businesses-list"),
    url(r'^dashboard/reviews/', include("reviews.urls", namespace="reviews")),

    url(r'^(?P<slug>[\w-]+)/$', business_detail, name="business-detail"),
    url(r'^activities/(?P<slug>[\w-]+)/services/$', services_list, name="services-list"),
    url(r'^services/calendar-json/$', occurences_json, name="occurences-json"),
    url(r'^activities/(?P<slug>[\w-]+)/services/create/', services_create, name="services-add"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/edit/', services_edit, name="services-edit"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/delete/', services_delete, name="services-delete"),
    ## Not needed for now, maybe in the future
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^spotimist/', include("spotimist_api.urls", namespace="spotimist-api")),
]

# When going into production we need to enable staticfiles collection into a separate folder/server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

reviews/models.py
from django.db import models
from django.conf import settings
from business.models import Business
# Create your models here.

class Review(models.Model):
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5
    RATINGS_CHOICES = (
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5'),
    )
    class Meta:
        verbose_name_plural = "reviews"
        ordering = ["-created"]
    title = models.CharField(max_length=120)
    content_positive = models.TextField()
    content_negative = models.TextField(blank=True, null=True)
    helpful_count = models.IntegerField(blank=True, null=True)
    rating = models.IntegerField(
        choices=RATINGS_CHOICES,
        default=ONE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="reviews")
    business = models.ForeignKey(Business, related_name="reviews")
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)

reviews/forms.py
from django import forms
from .models import Review
from django.utils.translation import gettext_lazy as _

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "content_positive",
            "content_negative",
            "rating",
            ]
        labels = {
            'content_positive': _('Pros'),
            'content_negative': _('Cons'),
        }
        widgets = {
            "rating": forms.NumberInput(attrs={'class': 'hidden', 'id': 'rating'}),
        }

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404
from bookings.models import Booking
from .forms import ReviewForm
from spotimist import settings
from pytz import timezone
import datetime

# Create your views here.


def reviews_list(request):
    
    reviews = request.user.reviews.all()

    bookings_to_review = request.user.bookings.filter(reviewed=False, date_from__lt=datetime.datetime.now(timezone(str(settings.TIME_ZONE))))

    context = {
        "reviews": reviews,
        "bookings_to_review": bookings_to_review
    }

    return render(request, "reviews/index.html", context )


def create_review(request, pk):

    booking = get_object_or_404(Booking, pk=pk)

    # if booking doesn't belong to the logged in user and if review has been left already then raise 404
    if booking.reviewed or booking.user != request.user:
        raise Http404        

    if request.method=='POST':

        review_form = ReviewForm(request.POST or None)

        if review_form.is_valid():
            instance = review_form.save(commit=False)
            instance.user = request.user
            instance.business = booking.business
            booking.reviewed = True
            booking.save()
            instance.save()

            messages.success(request, 'Review added successfully!', extra_tags="review_added")
            return redirect ("reviews:list_my_reviews")
    else:
        review_form = ReviewForm()
    
    context = {
        "form": review_form,
        "business_review": "{} at {}".format(booking.get_booked_activity(), booking.business)
    }

    return render(request, "reviews/create.html", context )

    

def edit_review(request):
    return ""

def delete_review(request):
    return ""

reviews/templates/reviews/create.html
{% extends "base-dashboard.html" %} {% load i18n %} {% load static %}
<!-- TODO

	

-->
{% block stylesheets %}
{{ block.super }}

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

{%endblock%}
{% block content %}

<!-- Content
	================================================== -->
<div class="dashboard-content">

    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12">
                <h2>Leave a Review</h2>
                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul><li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li>Reviews</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-12">

            <div id="add-listing">

                <!-- Section -->
                <div class="add-listing-section">
                    <form id="reviewForm" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Headline -->
                        <div class="add-listing-headline">
                            <h3>
                                <i class="sl sl-icon-doc"></i> {{business_review}}</h3>
                        </div>

                        <!-- Title -->
                        <div class="row with-forms">

                            <h5>Your Rating</h5>
                            <div class="form-group">
                                {{ form.rating }}

                                <div class="clearfix"></div>
                                <div class="leave-rating margin-bottom-30">
                                    <input type="radio" name="rating" id="rating-5" value="5"/>
                                    <label for="rating-5" class="fa fa-star"></label>
                                    <input type="radio" name="rating" id="rating-4" value="4"/>
                                    <label for="rating-4" class="fa fa-star"></label>
                                    <input checked type="radio" name="rating" id="rating-3" value="3"/>
                                    <label for="rating-3" class="fa fa-star"></label>
                                    <input type="radio" name="rating" id="rating-2" value="2"/>
                                    <label for="rating-2" class="fa fa-star"></label>
                                    <input type="radio" name="rating" id="rating-1" value="1"/>
                                    <label for="rating-1" class="fa fa-star"></label>
                                </div>

                                <div class="clearfix"></div>
                            </div>

                            <h5>Title</h5>
                            <div class="form-group">
                                {{ form.title.errors }} {{ form.title }}
                            </div>

                            <h5>Description</h5>
                            <div class="form-group">
                                {{ form.content_positive.errors }} {{ form.content_positive }}
                            </div>


                        </div>


                        <!-- Section / End -->

                        <input type="submit" id="submitReview" name="submit-submission" value="Continue"
                               class="button margin-top-30"/>

                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
<!-- Content / End -->

{% endblock content %}

{% block javascripts %}
{{ block.super }}

<script>
    $('.leave-rating input').change(function () {
        var radio = $(this).val();
        $('#rating').val(radio);
    });

</script>
{% endblock javascripts %}

reviews/templates/reviews/index.html
{% extends "base-dashboard.html" %} {% load i18n %} {% load static %}
<!-- TODO

	

-->
{% block content %}

<!-- Content
	================================================== -->
	<div class="dashboard-content">

	<!-- Titlebar -->
	<div id="titlebar">
		<div class="row">
			<div class="col-md-12">
				<h2>Reviews</h2>
				<!-- Breadcrumbs -->
				<nav id="breadcrumbs">
                    <ul><li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
						<li>Reviews</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<div class="row">

			{% if messages %}
				{% for message in messages %}
					{% ifequal message.tags "review_added success" %}
						<div class="col-md-12">
							<div class="notification success closeable">
								<p> {{message}}</p>
								<a class="close"></a>
							</div>
						</div>
					{% endifequal %}
				{% endfor %}
			{% endif %}

		<!-- Listings -->
		<div class="col-lg-12 col-md-12">

			{% if bookings_to_review %}
				<div class="dashboard-list-box margin-top-0 margin-bottom-20">
					<h4>Reviews to leave</h4>
					<ul>
						{% for booking in bookings_to_review %}

							{% comment %} <li><a href="{% url "booking_detail" pk=booking.pk %}">{{ booking }}</a></li> {% endcomment %}

							<li class="pending-booking">
								<div class="list-box-listing bookings">

									<div class="list-box-listing-content">
										<div class="inner">
											<h3>
												{{booking.get_booked_activity}} at {{ booking.business }}
											</h3>

											<div class="inner-booking-list">
													<h5>Date:</h5>
													<ul class="booking-list">
														<li class="">{{booking.date_from|date:"d F y"}}</li>
													</ul>
												</div>

											<a href="{% url 'reviews:create' pk=booking.pk %}" class="rate-review ">
												<i class="sl sl-icon-envelope-open"></i> Leave a Review</a>

										</div>
									</div>
								</div>
								{% comment %} <div class="buttons-to-right">
									<a href="#" class="button gray reject">
										<i class="sl sl-icon-close"></i> Cancel</a>
									<a href="#" class="button gray approve">
										<i class="sl sl-icon-check"></i> Approve</a>
								</div> {% endcomment %}
							</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}


			<div class="dashboard-list-box margin-top-0">

				<!-- Sort by -->
				<!-- <div class="sort-by">
					<div class="sort-by-select">
						<select data-placeholder="Default order" class="chosen-select-no-single">
							<option>Any Status</option>
							<option>Approved</option>
							<option>Pending</option>
							<option>Canceled</option>
						</select>
					</div>
				</div> -->

				<h4>Reviews List</h4>
				<ul>
					{% for review in reviews %}

						{% comment %} <li><a href="{% url "booking_detail" pk=booking.pk %}">{{ booking }}</a></li> {% endcomment %}

						<li class="pending-booking">
							<div class="list-box-listing bookings">

								<div class="list-box-listing-content">
									<div class="inner">
										<h3>
											{{review.title}}
										</h3>

										<div class="inner-booking-list">
											<h5>Business:</h5>
											<ul class="booking-list">
												<li class="highlighted">{{ review.business }}</li>
											</ul>
										</div>

										<div class="inner-booking-list">
												<h5>Date:</h5>
												<ul class="booking-list">
													<li class="highlighted">{{review.created|date:"d F y"}}</li>
												</ul>
											</div>

										<div class="inner-booking-list">
											<h5>Rating:</h5>
											<div class="star-rating" style="display: inline-flex" data-rating="{{review.rating}}">
											</div>

										</div>

										{% comment %} <a href="#small-dialog" class="rate-review popup-with-zoom-anim">
											<i class="sl sl-icon-envelope-open"></i> Send Message</a> {% endcomment %}

									</div>
								</div>
							</div>
							{% comment %} <div class="buttons-to-right">
								<a href="#" class="button gray reject">
									<i class="sl sl-icon-close"></i> Cancel</a>
								<a href="#" class="button gray approve">
									<i class="sl sl-icon-check"></i> Approve</a>
							</div> {% endcomment %}
						</li>
					{% endfor %}





				</ul>
			</div>
		</div>

	</div>

	</div>
	<!-- Content / End -->

{% endblock content %}