activities/urls.py
"""
URLs configuration for Activities 

"""
from django.conf.urls import url

from . import views
from services.views import services_create

urlpatterns = [
    # ur    l(r'^$', views.activities_list, name="list"),
    url(r'^my-activities/$', views.my_activities_list, name="my-list"),
    url(r'^create/$', views.activities_create, name="create"),
    url(r'^get-activities-map/$', views.activities_map, name="get_activities_map"),
    # url(r'^(?P<slug>[\w-]+)/$', views.activities_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit$', views.activities_update, name="edit"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.activities_delete, name="delete"),
    # url(r'^(?P<slug>[\w-]+)/services/create$', services_create, name="service-create"),
]

reviews/urls.py
"""
URLs configuration for Reviews 

"""
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^my-reviews/$', views.reviews_list, name="list_my_reviews"),
    url(r'^business-reviews/$', views.reviews_list, name="list_business_reviews"),
    url(r'^create/(?P<pk>\d+)/$', views.create_review, name="create"),
    url(r'^(?P<pk>\d+)/edit$', views.edit_review, name="edit"),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_review, name="delete"),
]

spotimist/urls.py
from business import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from activities.views import (
    home_page,
    home_about_page,
    dashboard,
    dashboard_business,
    dashboard_user_activities,
    blog_page,
    blog_post,
    get_listed,
    home_page_v2
)

from business.views import business_detail, dashboard_get_app
from business.serializers import BusinessViewSet, BusinessList, BusinessDetail, CategoryViewSet
from services.models import RecurringService, Occurrence
from services.views import services_list, services_create, services_edit, services_delete, occurences_json

from bookings.serializers import BookingDetail, BookingItemDetail

from activities.models import Activity, OpeningHours
from activities.seralizers import ActivityViewSet
from services.serializers import RecurringServiceViewSet
from rest_framework import routers, serializers, viewsets, generics

from support.views import contact_form, support_list, support_detail


# Routers provide an easy way of automatically determining the URL conf.

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
router.register(r'activities', ActivityViewSet)
# router.register(r'businesses', BusinessViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'recurring-services', RecurringServiceViewSet)
# router.register(r'openinghours', OpeningHoursViewSet)

if settings.ENABLE_TWO_FACTOR_ADMIN:
    from django_otp.admin import OTPAdminSite
    admin.site.__class__ = OTPAdminSite

urlpatterns = [
    url(r'^$', home_page_v2, name='home'),
    
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include("accounts.urls", namespace="profile")),
    url(r'^home-v2/', home_page, name='home-v2'),
    url(r'^home-about/', home_about_page, name='home-about'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^dashboard-business/$', dashboard_business, name='dashboard-business'),
    url(r'^dashboard-business/get-app/', dashboard_get_app, name='dashboard-get-app'),
    url(r'^dashboard/my-activities/$', dashboard_user_activities, name='dashboard_user_activities'),
    url(r'^blog/', blog_page, name='blog'),
    url(r'^spotimist-day-1/', blog_post, name='blog_post'),
    url(r'^dashboard/support/$', support_list, name='support_list'),
    url(r'^dashboard/support/(?P<pk>[0-9]+)/$', support_detail, name='support_detail'),
    url(r'^contact/', contact_form, name='contact'),
    url(r'^get-listed/', get_listed, name='get-listed'),

    url(r'^activities/', include("activities.urls", namespace="activities")),
    url(r'^bookings/', include("bookings.urls", namespace="bookings")),
    url(r'^business/', include("business.urls", namespace="business")),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^spotmin/', admin.site.urls),
    url(r'^privacy-policy/', TemplateView.as_view(template_name="privacy_policy.html"), name='privacy'),
    url(r'^terms-and-conditions/', TemplateView.as_view(template_name="terms_and_conditions.html"), name='tandc'),
    url(r'^booking-terms-and-conditions/', TemplateView.as_view(template_name="booking_terms_and_conditions.html"),
        name='btandc'),

    url(r'api/businesses/$', BusinessList.as_view(), name="api-business-list"),
    url(r'api/business-detail/(?P<pk>[0-9]+)/$', BusinessDetail.as_view(), name="business-detail"),
    url(r'api/booking-detail/(?P<booking_id>\w+)/(?P<business_id>[0-9]+)/$', BookingDetail.as_view(),
        name="booking-detail"),
    url(r'api/bookingitem-detail/(?P<pk>[0-9]+)/$', BookingItemDetail.as_view(), name="bookingitem-detail"),
    url(r'api/', include(router.urls)),
    url(r'^rest-auth/', include('rest_auth.urls')),

    url(r'listings/', views.FilterView.as_view(), name="businesses-list"),
    url(r'^dashboard/reviews/', include("reviews.urls", namespace="reviews")),

    url(r'^(?P<slug>[\w-]+)/$', business_detail, name="business-detail"),
    url(r'^activities/(?P<slug>[\w-]+)/services/$', services_list, name="services-list"),
    url(r'^services/calendar-json/$', occurences_json, name="occurences-json"),
    url(r'^activities/(?P<slug>[\w-]+)/services/create/', services_create, name="services-add"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/edit/', services_edit, name="services-edit"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/delete/', services_delete, name="services-delete"),
    ## Not needed for now, maybe in the future
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^spotimist/', include("spotimist_api.urls", namespace="spotimist-api")),
]

# When going into production we need to enable staticfiles collection into a separate folder/server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

activities/views.py
"""
Here is where we declare our views driven by controllers
"""
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.template.loader import get_template

from services.models import RecurringService
from .forms import ActivityForm
from .models import Activity, OpeningHours
from reviews.models import Review
from reviews.forms import ReviewForm
from business.models import Business
from categories.models import Category
from django.conf import settings
import datetime


def home_page(request):
    queryset = Business.objects.filter(is_active=True)[:12]
    context = {
        "object_list": queryset,
        "api_url": reverse('api-business-list')
    }
    return render(request, "home.html", context)


def home_about_page(request):
    # queryset = Business.objects.filter(is_active=True)[:12]
    # context = {
    #     "object_list": queryset,
    #     "api_url": reverse('api-business-list')
    # }
    return render(request, "home-about.html")

@login_required
def dashboard(request):
    today = datetime.datetime.today()
    bookings = request.user.get_activities_booked().filter(date_from__gte=today).order_by('date_from')
    queryset = Business.objects.filter(is_active=True)[:12]

    reviews = Review.objects.filter(user=request.user).count()

    context = {
        "bookings": bookings[:2],
        "bookings_count": bookings.count(),
        "reviews_count": reviews,

    }
    return render(request, "activity/dashboard.html", context)

@login_required
def dashboard_business(request):
    business = request.user.business.first()

    activities_count = Activity.objects.filter(business=business).count()
    bookings_count = business.bookings.count()

    activities_count = activities_count
    bookings_count = bookings_count
    current_date = datetime.datetime.now().date()
    alert_business = Business.objects.get(user=request.user)
    alert_activity = Activity.objects.filter(business=alert_business)
    activity_array = []
    # for alert in alert_activity:
    #     alert_service = RecurringService.objects.filter(activity=alert, end_repeat__lt=current_date)
    #     if alert_service.exists():
    #         activity_array.append(alert_service)
    # print(activity_array, "11111111111")
    for alert in alert_activity:
        for i in RecurringService.objects.filter(activity=alert):
            array = []
            temp_array = []
            end_repeat = str(i.end_repeat)
            for end in end_repeat.split(','):
                if end not in temp_array:
                    array.append(end)
                    temp_array.append(end)
            try:
                sort_array = sorted(array, key=lambda x: datetime.datetime.strptime(x, '%d/%m/%Y'))
            except:
                sort_array = sorted(array, key=lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))
            for s_array in sort_array[-1:]:
                try:
                    s_date = datetime.datetime.strptime(s_array, '%d/%m/%Y').strftime('%Y-%m-%d')
                except:
                    s_date = datetime.datetime.strptime(s_array, '%Y-%m-%d').strftime('%Y-%m-%d')
                n_date = datetime.datetime.strptime(s_date, '%Y-%m-%d').date()
                if n_date < current_date:
                    activity_array.append(i)

    context = {
        "activities_count": activities_count,
        "bookings_count": bookings_count,
        "reviews_count": business.get_reviews_count(),
        "alert_service": activity_array,
        "activities": alert_activity
    }
    return render(request, "activity/dashboard-business.html", context)


def blog_page(request):
    context = {
        "linkedin_url": settings.LINKEDIN_URL,
        "facebook_url": settings.FACEBOOK_URL
    }

    return render(request, "blog.html", context)


def blog_post(request):
    context = {
        "linkedin_url": settings.LINKEDIN_URL,
        "facebook_url": settings.FACEBOOK_URL
    }

    return render(request, "blog-post1.html", context)


def contact_page(request):
    return render(request, "contact.html")


def home_page_v2(request):
    queryset = Business.objects.filter(is_active=True)
    current_date = datetime.datetime.now().date()
    temp_location_array = []
    location_array = []
    for buss in queryset:
        get_activity = Activity.objects.filter(business=buss)
        if get_activity:
            for i in get_activity:
                for i in RecurringService.objects.filter(activity=i, is_archived=False):
                    array = []
                    temp_array = []
                    end_repeat = str(i.end_repeat)
                    for end in end_repeat.split(','):
                        if end not in temp_array:
                            array.append(end)
                            temp_array.append(end)
                    try:
                        sort_array = sorted(array, key=lambda x: datetime.datetime.strptime(x, '%d/%m/%Y'))
                    except:
                        sort_array = sorted(array, key=lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))
                    for s_array in sort_array[-1:]:
                        try:
                            s_date = datetime.datetime.strptime(s_array, '%d/%m/%Y').strftime('%Y-%m-%d')
                        except:
                            s_date = datetime.datetime.strptime(s_array, '%Y-%m-%d').strftime('%Y-%m-%d')
                        n_date = datetime.datetime.strptime(s_date, '%Y-%m-%d').date()
                        if n_date >= current_date:
                            if buss not in temp_location_array:
                                location_array.append(buss)
                                temp_location_array.append(buss)
    queryset = location_array

    categories = Category.objects.filter(active=True)
    context = {
        "object_list": queryset[:12],
        "categories": categories
    }
    return render(request, "home.html", context)


def get_listed(request):
    queryset = Business.objects.filter(is_active=True)[:12]
    categories = Category.objects.filter(active=True)
    context = {
        "object_list": queryset,
        "categories": categories
    }
    return render(request, "get-listed.html", context)


@login_required
def activities_create(request):
    form = ActivityForm(request.POST or None, request.FILES or None)
    business = get_object_or_404(Business, user=request.user)
    if form.is_valid():
        instance = form.save(commit=False)
        # instance.user = request.user
        instance.business = business
        instance.latitude = business.latitude
        instance.longitude = business.longitude
        instance.address = business.address
        instance.postCode = business.postCode
        instance.city = business.city
        instance.country = business.country
        instance.save()
        form.save_m2m()
        business.set_status(True)
        # message success
        messages.success(request, "Successfully Created")
        return redirect('activities:my-list')
    # else:
    #     messages.error(request, "Not Successfully Created")
    context = {
        "form": form,
    }
    return render(request, "activity/create.html", context)


def activities_detail(request, slug):
    activity = get_object_or_404(Activity, slug=slug)
    review_form = ReviewForm(request.POST or None)
    if review_form.is_valid():
        instance = review_form.save(commit=False)
        instance.user = request.user
        instance.activity = activity
        instance.save()
        return HttpResponseRedirect(activity.get_absolute_url())

    reviews = Review.objects.filter(activity__id=activity.id)
    opening_hours = OpeningHours.objects.filter(activity__id=activity.id)
    context = {
        "activity": activity,
        "reviews": reviews,
        "opening_hours": opening_hours,
        "form": review_form,
    }

    return render(request, "activity/detail.html", context)


def activities_list(request):
    queryset_list = Activity.objects.all()

    paginator = Paginator(queryset_list, 10)  # Show 25 activies per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "Activities List",
        "page_request_var": page_request_var,
        "activities_count": queryset_list.count()
    }

    return render(request, "activity/index.html", context)


@login_required
def my_activities_list(request):
    if request.user.has_business():
        business = Business.objects.get(user=request.user)
        queryset_list = Activity.objects.filter(business=business)

        paginator = Paginator(queryset_list, 10)  # Show 25 activies per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        context = {
            "object_list": queryset,
            "title": "Activities List",
            "page_request_var": page_request_var
        }

activities/templates/activity/create.html
{% extends "base-dashboard.html" %} {% load static %}
{% block content %}

<!-- Content
================================================== -->
<div class="dashboard-content">

    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12">
                <h2>Add an activity</h2>
                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li>
                            <a href="{% url 'home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
                        <li>Add an activity</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

    {% if form.description.errors %}
    <div class="notification error closeable">
        <p>{{ form.description.errors }}</p>
        <a class="close"></a>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-lg-12">

            <div id="add-listing">

                <!-- Section -->
                <div class="add-listing-section">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Headline -->
                        <div class="add-listing-headline">
                            <h3>
                                <i class="sl sl-icon-doc"></i> Basic Information</h3>
                        </div>

                        <!-- Title -->
                        <div class="row with-forms">
                            <div class="col-md-12">
                                <h5>Activity Name<i class="tip"
                                       data-tip-content="The activity name should reflect the main activity of your business (e.g.'Cooking class', 'Dance class', 'City tour')"></i><i class="info-required">*</i>
                                </h5>
                                <div class="form-group">
                                    {{ form.name.errors }} {{ form.name }}
                                </div>
                            </div>
                            <!-- Type -->
                            {% comment %} <div class="col-md-6">
                                <h5>Keywords
                                    <i class="tip"
                                       data-tip-content="Maximum of 15 keywords related with your activity"></i>
                                </h5>
                                <input type="text" placeholder="Keywords should be separated by commas">
                            </div> {% endcomment %}

                        </div>


                        <!-- Checkboxes -->
                        <h5 class="margin-top-30 margin-bottom-10">Categories<i class="tip"
                            data-tip-content="Choose relevant categories, they are used as guidance to refine researches"></i><i class="info-required">*</i>
                    </h5>

                        <div class="checkboxes in-row margin-bottom-20">

                            {% for category in form.categories %}

                            {{ category.tag }}
                            <label for="{{ category.id_for_label }}">{{ category.choice_label }}</label>

                            {% endfor %}

                        </div>
                        <!-- Checkboxes / End -->

                </div>
                <!-- Section / End -->

                <!-- Section -->
                <div class="add-listing-section margin-top-45">

                    <!-- Headline -->
                    <div class="add-listing-headline">
                        <h3>
                            <i class="sl sl-icon-docs"></i> Details</h3>
                    </div>

                    <!-- Description -->
                    <div class="form">
                        <div class="form-group">
                             {{ form.description.label_tag }} {{ form.description }}
                        </div>
                    </div>

                </div>


                <input type="submit" name="submit-submission" value="Continue" class="button margin-top-30"/>

                </form>
            </div>
        </div>


    </div>

</div>
<!-- Content / End -->


{% endblock content %}


<!-- Scripts
================================================== -->

{% block javascripts %} {{ block.super }}

{% endblock javascripts %}

activities/templates/activity/dashboard-business.html
{% extends "base-dashboard.html" %} {% load static %}
<!-- 

TODO:

-List activities
-List upcoming bookings

-->
{% block content %}


<!-- Content
================================================== -->
<div class="dashboard-content">

    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12">
                <h2>Dashboard</h2>
                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>Dashboard</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!--Alert-->
    {% if alert_service %}
    <div class="notification error" role="alert">
        <strong>
            {% for alert in alert_service %}
                    {{alert}}
            {% if not forloop.last %} , {% endif %}
            {% endfor %}
        </strong> Service date expired, please reset your service date...
    </div>
    {% endif %}

    {% if activities_count == 0 %}
    <div class="notification error" role="alert">
        You haven't created any activity yet, click <a style="text-decoration: underline;" href="{% url 'activities:create' %}">here</a> to add one.
    </div>
    {% endif %}

    {% for activity in activities %}
        {% if activity.has_services == False %}
        <div class="notification error" role="alert">
            <strong>{{activity}}</strong> has no service yet, click <a style="text-decoration: underline;" href="{% url 'services-add' activity.slug %}">here</a> to add one.
        </div>
        {% endif %}
    {% endfor %}

    {% if user.has_business %}
    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12 margin-top-30">
                <span>Business Panel Dashboard</span>
            </div>
        </div>
    </div>

    <!-- Content -->
    <div class="row">

        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-1">
                <div class="dashboard-stat-content">
                    <h4>{{activities_count}}</h4>
                    <span>Active Listings</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Map2"></i>
                </div>
            </div>
        </div>

        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-2">
                <div class="dashboard-stat-content">
                    <h4>{{bookings_count}}</h4>
                    <span>Bookings</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Calendar-4"></i>
                </div>
            </div>
        </div>


        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-3">
                <div class="dashboard-stat-content">
                    <h4>{{reviews_count}}</h4>
                    <span>Total Reviews</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Add-UserStar"></i>
                </div>
            </div>
        </div>

        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-4">
                <div class="dashboard-stat-content">
                    <h4>0</h4>
                    <span>Times Bookmarked</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Heart"></i>
                </div>
            </div>
        </div>
    </div>


    <div class="row">

        <!-- Active Listings -->
        <div class="col-lg-6 col-md-12">
            <div class="dashboard-list-box with-icons margin-top-20">
                <!-- <h4>Active Listings</h4>
                <ul>
                    <li>
                        <i class="list-box-icon sl sl-icon-star"></i> Jack Perry left a review
                        <div class="numerical-rating" data-rating="2.5"></div> on
                        <strong>
                            <a href="#">Tom's Restaurant</a>
                        </strong>
                        <a href="#" class="close-list-item">
                            <i class="fa fa-close"></i>
                        </a>
                    </li>
                </ul> -->
            </div>
        </div>

        <!-- Invoices --><!--
                <div class="col-lg-6 col-md-12">
                    <div class="dashboard-list-box invoices with-icons margin-top-20">
                        <h4>Invoices</h4>
                        <ul>

                            <li>
                                <i class="list-box-icon sl sl-icon-doc"></i>
                                <strong>Professional Plan</strong>
                                <ul>
                                    <li class="unpaid">Unpaid</li>
                                    <li>Order: #00124</li>
                                    <li>Date: 20/07/2017</li>
                                </ul>
                                <div class="buttons-to-right">
                                    <a href="dashboard-invoice.html" class="button gray">View Invoice</a>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
            

        -->
    {% endif %}
    </div>

</div>
<!-- Content / End -->

{% endblock content %}


<!-- Scripts
================================================== -->

{% block javascripts %} {{ block.super }} {% endblock javascripts %}

activities/templates/activity/dashboard.html
{% extends "base-dashboard.html" %}
<!-- 

TODO:

-Add profile picture link available all pages ( So far only on "My Profile" page)
-test access from non authenticated uers
-Fill data dynamically

-->
{% block content %}
<!-- Content
================================================== -->
<div class="dashboard-content">

    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12">
                <h2>Dashboard</h2>
                <!-- Breadcrumbs -->
                <nav id="breadcrumbs">
                    <ul>
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>Dashboard</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>


    <!-- Titlebar -->
    <div id="titlebar">
        <div class="row">
            <div class="col-md-12 margin-top-30">
                <span>User Panel Dashboard</span>
            </div>
        </div>
    </div>


    <!-- Content -->
    <div class="row">

        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-1">
                <div class="dashboard-stat-content">
                    <h4>{{bookings_count}}</h4>
                    <span>Activity planned</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Map2"></i>
                </div>
            </div>
        </div>

        <!-- Item -->
        <!-- <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-2">
                <div class="dashboard-stat-content">
                    <h4>0</h4>
                    <span>Subscription</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Calendar-4"></i>
                </div>
            </div>
        </div> -->


        <!-- Item -->
        <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-3">
                <div class="dashboard-stat-content">
                    <h4>{{reviews_count}}</h4>
                    <span>Reviews</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Add-UserStar"></i>
                </div>
            </div>
        </div>

        <!-- Item -->
        <!-- <div class="col-lg-3 col-md-6">
            <div class="dashboard-stat color-4">
                <div class="dashboard-stat-content">
                    <h4>0</h4>
                    <span>Bookmarked</span>
                </div>
                <div class="dashboard-stat-icon">
                    <i class="im im-icon-Heart"></i>
                </div>
            </div>
        </div> -->
    </div>


    <div class="row">

        <!-- Recent Activity -->
        <div class="col-lg-6 col-md-12">
            <div class="dashboard-list-box with-icons margin-top-20">
                <h4>Upcoming Activities</h4>
                <ul>
                    {% for booking in bookings %}
                    <li>
                        <i class="list-box-icon sl sl-icon-layers"></i>
                        {{booking.get_booked_activity}} at
                        <strong>
                            <a href="#">{{booking.business}}</a>
                        </strong>
                        - {{booking.date_from|date:"d F y"}}
                    </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

    </div>

</div>
<!-- Content / End -->

{% endblock content %}

<!-- Scripts
================================================== -->

{% block javascripts %} {{ block.super }}

{% endblock javascripts %}