accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.user_detail, name="user-detail"),
    url(r'^change-psw/$', views.change_psw, name="change-psw"),
    url(r'^upload-profile-picture/$', views.upload_profile_picture, name="upload-profile-image"),
]

business/urls.py
"""
URLs configuration for Activities 

"""
from django.conf.urls import url
from allauth.account.views import LoginView, SignupView 
from . import views

urlpatterns = [
    url(r'^activities/$', views.business_activities, name="activities"),
    url(r'^register/$', views.business_create, name="create"),
    url(r'^profile/$', views.business_profile_edit, name="profile-edit"),
    url(r'^business-image-delete/$', views.delete_business_image, name="business-image-delete"),
    url(r'^business-image-upload/$', views.upload_business_image, name="business-image-upload"),
]

reviews/urls.py
"""
URLs configuration for Reviews 

"""
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^my-reviews/$', views.reviews_list, name="list_my_reviews"),
    url(r'^business-reviews/$', views.reviews_list, name="list_business_reviews"),
    url(r'^create/(?P<pk>\d+)/$', views.create_review, name="create"),
    url(r'^(?P<pk>\d+)/edit$', views.edit_review, name="edit"),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_review, name="delete"),
]

spotimist/urls.py
from business import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from activities.views import (
    home_page,
    home_about_page,
    dashboard,
    dashboard_business,
    dashboard_user_activities,
    blog_page,
    blog_post,
    get_listed,
    home_page_v2
)

from business.views import business_detail, dashboard_get_app
from business.serializers import BusinessViewSet, BusinessList, BusinessDetail, CategoryViewSet
from services.models import RecurringService, Occurrence
from services.views import services_list, services_create, services_edit, services_delete, occurences_json

from bookings.serializers import BookingDetail, BookingItemDetail

from activities.models import Activity, OpeningHours
from activities.seralizers import ActivityViewSet
from services.serializers import RecurringServiceViewSet
from rest_framework import routers, serializers, viewsets, generics

from support.views import contact_form, support_list, support_detail


# Routers provide an easy way of automatically determining the URL conf.

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
router.register(r'activities', ActivityViewSet)
# router.register(r'businesses', BusinessViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'recurring-services', RecurringServiceViewSet)
# router.register(r'openinghours', OpeningHoursViewSet)

if settings.ENABLE_TWO_FACTOR_ADMIN:
    from django_otp.admin import OTPAdminSite
    admin.site.__class__ = OTPAdminSite

urlpatterns = [
    url(r'^$', home_page_v2, name='home'),
    
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include("accounts.urls", namespace="profile")),
    url(r'^home-v2/', home_page, name='home-v2'),
    url(r'^home-about/', home_about_page, name='home-about'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^dashboard-business/$', dashboard_business, name='dashboard-business'),
    url(r'^dashboard-business/get-app/', dashboard_get_app, name='dashboard-get-app'),
    url(r'^dashboard/my-activities/$', dashboard_user_activities, name='dashboard_user_activities'),
    url(r'^blog/', blog_page, name='blog'),
    url(r'^spotimist-day-1/', blog_post, name='blog_post'),
    url(r'^dashboard/support/$', support_list, name='support_list'),
    url(r'^dashboard/support/(?P<pk>[0-9]+)/$', support_detail, name='support_detail'),
    url(r'^contact/', contact_form, name='contact'),
    url(r'^get-listed/', get_listed, name='get-listed'),

    url(r'^activities/', include("activities.urls", namespace="activities")),
    url(r'^bookings/', include("bookings.urls", namespace="bookings")),
    url(r'^business/', include("business.urls", namespace="business")),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^spotmin/', admin.site.urls),
    url(r'^privacy-policy/', TemplateView.as_view(template_name="privacy_policy.html"), name='privacy'),
    url(r'^terms-and-conditions/', TemplateView.as_view(template_name="terms_and_conditions.html"), name='tandc'),
    url(r'^booking-terms-and-conditions/', TemplateView.as_view(template_name="booking_terms_and_conditions.html"),
        name='btandc'),

    url(r'api/businesses/$', BusinessList.as_view(), name="api-business-list"),
    url(r'api/business-detail/(?P<pk>[0-9]+)/$', BusinessDetail.as_view(), name="business-detail"),
    url(r'api/booking-detail/(?P<booking_id>\w+)/(?P<business_id>[0-9]+)/$', BookingDetail.as_view(),
        name="booking-detail"),
    url(r'api/bookingitem-detail/(?P<pk>[0-9]+)/$', BookingItemDetail.as_view(), name="bookingitem-detail"),
    url(r'api/', include(router.urls)),
    url(r'^rest-auth/', include('rest_auth.urls')),

    url(r'listings/', views.FilterView.as_view(), name="businesses-list"),
    url(r'^dashboard/reviews/', include("reviews.urls", namespace="reviews")),

    url(r'^(?P<slug>[\w-]+)/$', business_detail, name="business-detail"),
    url(r'^activities/(?P<slug>[\w-]+)/services/$', services_list, name="services-list"),
    url(r'^services/calendar-json/$', occurences_json, name="occurences-json"),
    url(r'^activities/(?P<slug>[\w-]+)/services/create/', services_create, name="services-add"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/edit/', services_edit, name="services-edit"),
    url(r'^activities/(?P<slug>[\w-]+)/services/(?P<id>[0-9]+)/delete/', services_delete, name="services-delete"),
    ## Not needed for now, maybe in the future
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^spotimist/', include("spotimist_api.urls", namespace="spotimist-api")),
]

# When going into production we need to enable staticfiles collection into a separate folder/server
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

accounts/forms.py
from django import forms

from django.contrib.auth.forms import ReadOnlyPasswordHashField
from allauth.account.forms import LoginForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import now
from django.contrib.auth.password_validation import validate_password
from allauth.account.utils import setup_user_email
from .models import Profile

User = get_user_model()


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]
        widgets = {
            "first_name": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            "last_name": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        validate_password(password1)
        return password2

    def signup(self, request, user):

        print ("here I sign up")

        # user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name']
        # user.save()

    def save(self, commit=True):

        print("Here I save")
        # Save the provided password in hashed format
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        from allauth.account.models import EmailAddress, EmailConfirmation, EmailConfirmationHMAC

        if commit:
            user.save()

        # Creating both email confirmation in the db and in the console - To be changed later 
        email_address = EmailAddress.objects.create(user=user, email=user.email, primary=True, verified=False)
        email_address.save()

        confirmation = EmailConfirmation.create(email_address)
        confirmation.sent = now()
        confirmation.save()

        confirmationHMAC = EmailConfirmationHMAC(email_address)
        confirmationHMAC.send()

        return user


# class CoreLoginForm(LoginForm):

#     def __init__(self, *args, **kwargs):
#         super(CoreLoginForm, self).__init__(*args, **kwargs)
#         ## here i add the new fields that i need
#         self.fields["email"] = forms.CharField(label=_('E-mail'), max_length=100,widget=forms.TextInput(
#                                    attrs={'placeholder': _('E-mail')}))


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    # password = ReadOnlyPasswordHashField()
    # password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    # password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]
        widgets = {
            "first_name": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            "last_name": forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }

    # def clean_password(self):
    #     # Regardless of what the user provides, return the initial value.
    #     # This is done here, rather than on the field, because the
    #     # field does not have access to the initial value
    #     # return self.initial["password"]
    #     print("clean password")
    #     # password1=self.cleaned_data.get('new_password')
    #     # password2=self.cleaned_data.get('reenter_password')

    #     return self.cleaned_data #don't forget this.


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "image",
            "city",
            "country",
        ]

accounts/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.core.urlresolvers import reverse
from .models import CustomUser, Profile
from .forms import ProfileForm, SignupForm, UserChangeForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


# Create your views here.

def user_detail(request):
    user = get_object_or_404(CustomUser, id=request.user.id)
    profile = get_object_or_404(Profile, user=user)

    profile_form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    user_form = UserChangeForm(request.POST or None, request.FILES or None, instance=user)

    psw_form = PasswordChangeForm(request.user, prefix="pswfor")

    if request.method == 'POST':
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return HttpResponseRedirect(request.get_full_path())
        else:

            print("not valid")
            print(user_form.errors)
            print(profile_form.errors)

    context = {
        "user": user,
        "profile": profile,
        "user_form": user_form,
        "profile_form": profile_form,
        'psw_form': psw_form
    }

    return render(request, "profile/profile.html", context)


def change_psw(request):
    if request.method == 'POST':
        psw_form = PasswordChangeForm(request.user, request.POST, prefix="pswfor")
        if psw_form.is_valid():
            user = psw_form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!', extra_tags="password_changed")
            return redirect("profile:user-detail")
        else:
            messages.error(request, 'Please correct the error below.')
            user = get_object_or_404(CustomUser, id=request.user.id)
            profile = get_object_or_404(Profile, user=user)

            profile_form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
            user_form = UserChangeForm(request.POST or None, request.FILES or None, instance=user)

            return render(request, 'profile/profile.html', {
                "user": user,
                "profile": profile,
                "user_form": user_form,
                "profile_form": profile_form,
                "psw_form": psw_form
            })

    else:
        raise Http404

def upload_profile_picture(request):
    profile = get_object_or_404(Profile, user=request.user)
    
    try:
        files = [request.FILES.get('file')]
        
        for f in files:
            profile.image = f
            profile.save()

        return HttpResponse("OK")
    except Exception as e:
        print("error in upload " + str(e))

accounts/templates/profile/profile.html
{% extends "base-dashboard.html" %} {% load static %}

<!-->

=== TO DO ===

-Get the forms to work
-clean notes
-->

 {% block content %}

		<!-- Content
	================================================== -->
		<div class="dashboard-content">

			<!-- Titlebar -->
			<div id="titlebar">
				<div class="row">
					<div class="col-md-12">
						<h2>My Profile</h2>
						<!-- Breadcrumbs -->
						<nav id="breadcrumbs">
							<ul><li><a href="{% url 'home' %}">Home</a></li>
								<li><a href="{% url 'dashboard' %}">Dashboard</a></li>
								<li>My Profile</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
			
			<div class="row">

				{% if messages %}
            
                {% for message in messages %}
					{% ifequal message.tags "password_changed success" %}
					<div class="col-md-12">
						<div class="notification success closeable">
							<p> {{message}}</p>
							<a class="close"></a>
						</div>
					</div>
					
					{% endifequal %}
					
					{% endfor %}
				{% endif %}
				
				

				<!-- Profile -->
				<div class="{% if request.user.is_social %} col-lg-12 {% else %}col-md-12 col-lg-6 {% endif %}">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="dashboard-list-box margin-top-0">
							<h4 class="gray">Profile Details</h4>
							<div class="dashboard-list-box-static">

								<!-- Avatar -->

								<!-- Dropzone -->
								<div id="galleryDrop" class="dropzone">
									{% comment %} <input type="hidden" name="business" value="{{business.id}}"/> {% endcomment %}
									<!-- <form id="id_dropzone" action="{% url 'business:profile-edit' %}" class="dropzone"></form> -->
								</div>

								<!-- <div class="edit-profile-photo">
									<img src="/uploads/{{profile.image}}" alt="">
									<div class="change-photo-btn">
										<div class="photoUpload">
											<span>
												<i class="fa fa-upload"></i> Upload Photo</span>
											<input type="file" class="upload" />
										</div>
									</div>
								</div> -->

								<!-- Details -->
								<div class="my-profile">
									<div class="col-md-6">
										<label>First Name</label>
										<!-- <input value="{{request.user.first_name}}" type="text"> -->
										{{user_form.first_name}}
									</div>
									<div class="col-md-6">
										<label>Last Name</label>
										{{user_form.last_name}}
									</div>
									<div class="col-md-12">
										<label>Email</label>
										{{user_form.email}}
									
									<label>
										<i class="fa fa-twitter"></i> Twitter</label>
									<input placeholder="https://www.twitter.com/" type="text">

									<label>
										<i class="fa fa-facebook-square"></i> Facebook</label>
									<input placeholder="https://www.facebook.com/" type="text">

									<label>
										<i class="fa fa-google-plus"></i> Google+</label>
									<input placeholder="https://www.google.com/" type="text">
									</div>
								</div>

								<button type="submit" class="button margin-top-15 margin-left-20">Save Changes</button>

							</div>
						</div>
					</form>
				</div>

				{% if not request.user.is_social %}
					<!-- Change Password -->
					<div class="col-lg-6 col-md-12">
						<div class="dashboard-list-box margin-top-0">
							<h4 class="gray">Change Password</h4>
							<div class="dashboard-list-box-static">
								<form method="POST" action="{% url 'profile:change-psw' %}">
									{% csrf_token %}
									{{psw_form.old_password.label_tag }}
									{{psw_form.old_password }}
									{{psw_form.old_password.errors }}
									
									{{psw_form.new_password1.label_tag }}
									{{psw_form.new_password1 }}
									{{psw_form.new_password1.errors }}
									
									{{psw_form.new_password2.label_tag }}
									{{psw_form.new_password2 }}
									{{psw_form.new_password2.errors }}
									

									<!-- Change Password -->
									<!-- <div class="my-profile">
										<label class="margin-top-0">Current Password</label>
										<input type="password">

										<label>New Password</label>
										<input type="password">

										<label>Confirm New Password</label>
										<input type="password">

										<button type="submit" class="button margin-top-15">Change Password</button>
									</div> -->
								<button type="submit" class="button margin-top-15">Change Password</button>
							</form>
							</div>
						</div>
					</div>
				{% endif %}

				
				<!-- Copyrights -->
				<div class="col-md-12 margin-bottom-75">
					
				</div>

			</div>

		</div>
		<!-- Content / End -->
		{% endblock content %}




	<!-- Scripts
================================================== -->

	{% block javascripts %} 
	{{ block.super }} 
	<script type="text/javascript" src="{% static 'scripts/dropzone.js' %}"></script>
	
	

	<script type="text/javascript">

	function getCookie(name) {

		var cookieValue = null;
		if (document.cookie && document.cookie != '') {
			var cookies = document.cookie.split(';');
			for (var i = 0; i < cookies.length; i++) {
				var cookie = jQuery.trim(cookies[i]);
				// Does this cookie string begin with the name we want?
				if (cookie.substring(0, name.length + 1) == (name + '=')) {
					cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					break;
				}
			}
		}

		return cookieValue;

	}
	
	Dropzone.autoDiscover = false;
	var myDropzone = new Dropzone("div#galleryDrop", 
	{ 
		autoProcessQueue: true,
		clickable: true,
		resizeWidth: 400,
		headers: {
			'X-CSRFToken': getCookie('csrftoken')
		},
		url: "{% url 'profile:upload-profile-image' %}",
	});

	
	
	</script>
	{% endblock javascripts %}